version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: improvz
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./sql/01_create.sql:/docker-entrypoint-initdb.d/01_create.sql
    networks:
      - external_network

  apache:
    build:
      context: .
    container_name: apache_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - external_network
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      MYSQL_HOST: mysql_server
      MYSQL_DATABASE: improvz
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  sftp:
    image: atmoz/sftp:latest
    container_name: sftp_server
    restart: always
    ports:
      - "22:22"
    volumes:
      - ./web:/home/user/web
    environment:
      SFTP_USERS: "user:password:1001"
    depends_on:
      - mysql
      - apache
    networks:
      - external_network

networks:
  external_network:
    driver: bridge