-- MySQL Script generated by MySQL Workbench
-- Sat Jan 18 21:07:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema improvz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema improvz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `improvz` DEFAULT CHARACTER SET utf8 ;
USE `improvz` ;

-- -----------------------------------------------------
-- Table `improvz`.`IMP_Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `improvz`.`IMP_Client` ;

CREATE TABLE IF NOT EXISTS `improvz`.`IMP_Client` (
                                                      `CLI_ID` INT NOT NULL AUTO_INCREMENT,
                                                      `CLI_Nom` VARCHAR(64) NOT NULL,
                                                      `CLI_Prenom` VARCHAR(64) NOT NULL,
                                                      `CLI_Avatar` VARCHAR(10000) NULL DEFAULT 'https://placehold.co/32x32',
                                                      `CLI_Email` VARCHAR(45) NOT NULL,
                                                      `CLI_Numero` INT NOT NULL,
                                                      PRIMARY KEY (`CLI_ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `improvz`.`IMP_Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `improvz`.`IMP_Service` ;

CREATE TABLE IF NOT EXISTS `improvz`.`IMP_Service` (
                                                       `SER_ID` INT NOT NULL AUTO_INCREMENT,
                                                       `SER_Libelle` VARCHAR(64) NOT NULL,
                                                       PRIMARY KEY (`SER_ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `improvz`.`IMP_Type_Facturation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `improvz`.`IMP_Type_Facturation` ;

CREATE TABLE IF NOT EXISTS `improvz`.`IMP_Type_Facturation` (
                                                                `TYPF_ID` INT NOT NULL AUTO_INCREMENT,
                                                                `TYPF_Libelle` VARCHAR(64) NOT NULL,
                                                                PRIMARY KEY (`TYPF_ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `improvz`.`IMP_Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `improvz`.`IMP_Commande` ;

CREATE TABLE IF NOT EXISTS `improvz`.`IMP_Commande` (
                                                        `COM_ID` INT NOT NULL AUTO_INCREMENT,
                                                        `SER_ID` INT NOT NULL,
                                                        `COM_Libelle` VARCHAR(128) NOT NULL,
                                                        `COM_DATE_FACTURATION` DATE NOT NULL,
                                                        `CLI_ID` INT NOT NULL,
                                                        `COM_Facturation` INT NOT NULL,
                                                        `TYPF_ID` INT NOT NULL,
                                                        PRIMARY KEY (`COM_ID`),
                                                        INDEX `fk_IMP_Commande_IMP_Service_idx` (`SER_ID` ASC) VISIBLE,
                                                        INDEX `fk_IMP_Commande_IMP_Client1_idx` (`CLI_ID` ASC) VISIBLE,
                                                        INDEX `fk_IMP_Commande_IMP_Type_Facturation1_idx` (`TYPF_ID` ASC) VISIBLE,
                                                        CONSTRAINT `fk_IMP_Commande_IMP_Service`
                                                            FOREIGN KEY (`SER_ID`)
                                                                REFERENCES `improvz`.`IMP_Service` (`SER_ID`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_IMP_Commande_IMP_Client1`
                                                            FOREIGN KEY (`CLI_ID`)
                                                                REFERENCES `improvz`.`IMP_Client` (`CLI_ID`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_IMP_Commande_IMP_Type_Facturation1`
                                                            FOREIGN KEY (`TYPF_ID`)
                                                                REFERENCES `improvz`.`IMP_Type_Facturation` (`TYPF_ID`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `improvz`.`IMP_Avis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `improvz`.`IMP_Avis` ;

CREATE TABLE IF NOT EXISTS `improvz`.`IMP_Avis` (
                                                    `AVI_ID` INT NOT NULL AUTO_INCREMENT,
                                                    `COM_ID` INT NOT NULL,
                                                    `AVI_Avis` VARCHAR(256) NOT NULL,
                                                    `AVI_Note` INT NOT NULL,
                                                    PRIMARY KEY (`AVI_ID`),
                                                    INDEX `fk_IMP_Avis_IMP_Commande1_idx` (`COM_ID` ASC) VISIBLE,
                                                    CONSTRAINT `fk_IMP_Avis_IMP_Commande1`
                                                        FOREIGN KEY (`COM_ID`)
                                                            REFERENCES `improvz`.`IMP_Commande` (`COM_ID`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `improvz`.`IMP_Carte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `improvz`.`IMP_Carte` ;

CREATE TABLE IF NOT EXISTS `improvz`.`IMP_Carte` (
                                                     `CAR_ID` VARCHAR(64) NOT NULL,
                                                     `COM_ID` INT NULL,
                                                     `CAR_PREFIX` VARCHAR(4) NOT NULL,
                                                     `CAR_PRENOM` VARCHAR(32) NOT NULL,
                                                     `CAR_NOM` VARCHAR(32) NOT NULL,
                                                     `CAR_COMPANY_NAME` VARCHAR(64) NOT NULL,
                                                     `CAR_POSTE` VARCHAR(64) NOT NULL,
                                                     `CAR_WEBSITE` VARCHAR(64) NOT NULL,
                                                     `CAR_MAIL` VARCHAR(128) NOT NULL,
                                                     `CAR_PHONE` VARCHAR(128) NOT NULL,
                                                     `CAR_NOTES` VARCHAR(256) NOT NULL,
                                                     `CAR_SUFFIX` VARCHAR(64) NOT NULL,
                                                     `CAR_IMAGE` VARCHAR(10000) NOT NULL,
                                                     PRIMARY KEY (`CAR_ID`),
                                                     INDEX `fk_IMP_Carte_IMP_Commande1_idx` (`COM_ID` ASC) VISIBLE,
                                                     CONSTRAINT `fk_IMP_Carte_IMP_Commande1`
                                                         FOREIGN KEY (`COM_ID`)
                                                             REFERENCES `improvz`.`IMP_Commande` (`COM_ID`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
